
version: '3.0'

services:
  pihole:
    container_name: pihole_unbound
    image: cbcrowe/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      - 22/tcp # Uncomment to enable SSH
    environment:
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - /root/etc-pihole:/etc/pihole:rw
      - /root/etc-dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped
